### ISSUE TITLE
status should work for non-dockerized installs.

### ISSUE THREAD

**Issue by matthewdupre** [tigera/libcalico-go#138]
We should implement them in a way that works for dockerized (calico-node) and non-dockerized execution of felix / BIRD.  They at least should give sane looking output in both cases.  First thought is we could use `ps` to check felix / BIRD status - that should work regardless of how they're being ran.

**Comment by robbrockbank** [comment]
I think if this is required by a particular customer use case we should move up to P1

**Comment by matthewdupre** [comment]
It was.  It also applies to all of OpenStack.

**Comment by gunjan5** [comment]
Issue only for `status` command since `diags` doesn't really depend on a container runtime as per the discussion with @matthewdupre

**Comment by gunjan5** [comment]
Behavior with non-containerized installs with only IPv4 (no `bird6` running): 
```bash
$sudo calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.17.8.102 | node-to-node mesh | up    | 19:51:08 | Established |
+--------------+-------------------+-------+----------+-------------+

INFO: BIRDv6 process: 'bird6' is not running.
```

**Comment by matthewdupre** [comment]
LGTM :)
