### ISSUE TITLE
calicoctl won't create policy

### ISSUE THREAD

**Issue by djosborne** [tigera/libcalico-go#141]
```
$ bin/calicoctl create -f ./policy.yaml
Error processing input file: Unknown resource type (policy) and/or version (v1)
Error executing command: Unknown resource type (policy) and/or version (v1)
```

```
$ cat policy.yaml
apiVersion: v1
kind: policy
metadata:
  name: policy1
  tier: tier1
spec:
  order: 100
  selector: type=='database'
  ingress:
  - action: deny
```

**Comment by gunjan5** [comment]
Seems like as of this change: https://github.com/tigera/libcalico-go/commit/b4fd636e860597d8ccb2f06f501135d03e169bfb#diff-fcf1fd30667a4c28c65230985a8ace13R24

the config `.yaml` file `apiVersion` has to be `"1.0"`

I will open a PR to change all the `.yaml` files to use the new `apiVersion`

CC @robbrockbank

**Comment by gunjan5** [comment]
after some discussion with @robbrockbank , we are going back to `v1`, so you won't have to change the `.yaml` files and `apiVersion` can be `v1` (will open a new PR shortly)
